# Generated by Django 5.0.3 on 2024-03-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image_user_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_description',
        ),
    ]
